### ISSUE TITLE
I can't push the sass files up. 

### ISSUE THREAD

**Issue by Codingkj** [trends-team/digital-press#1]
I've created a new branch sass off master. Shows on local repository. 

Karens-MacBook-Air:digital-press kmusson$ git branch
  bottom1
  development
  master
- sass
  Karens-MacBook-Air:digital-press kmusson$ git remote
  origin
  Command> git push -u origin/master
  Error message:
  fatal: 'origin/master' does not appear to be a git repository
  fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by fedosejev** [comment]
@Codingkj most likely it's an internet access issue.

**Comment by Codingkj** [comment]
Yes, now resolved
